### ISSUE TITLE
Test suite failure with hspec 2.5

### ISSUE THREAD

**Issue by DanBurton** [louispan/pipes-misc#1]
```
> /tmp/stackage-build12/pipes-misc-0.4.0.1$ dist/build/pipes-misc-test/pipes-misc-test

Misc
  Buffered
  Locally +10 to second
pipes-misc-test: thread blocked indefinitely in an MVar operation
```

I was able to reproduce this like so:

```bash
stack unpack pipes-misc-0.4.0.1 && cd pipes-misc-0.4.0.1
edit stack.yaml # add the following stack.yaml
stack test
```

```yaml
# stack.yaml
resolver: nightly-2018-03-18
extra-deps:
- Decimal-0.5.1
- pipes-concurrency-2.0.10
```

However, note that the suite passes if an older version of hspec is used

```yaml
resolver: nightly-2018-03-18
extra-deps:
- hspec-2.4.8
- hspec-core-2.4.8
- hspec-discover-2.4.8
- Decimal-0.5.1
- pipes-concurrency-2.0.10
```

This is an unfortunate situation with ghc/hspec, and I'm not sure if there is a proper resolution to it.
See also: https://github.com/jcristovao/enclosed-exceptions/issues/12
